version: '3.8'

services:
  backend:
    build: ./backend # Django projesinin bulunduğu klasör yolu
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend # React projesinin bulunduğu klasör yolu
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules